import { ref } from 'vue'
import { allWords, tagLabels, tags } from '@/data'
import { serialize } from '@/data/serialize'
import type { Word } from '@/data'

/**
 * Dev-only editing of the in-memory vocabulary store. Mutations operate on the
 * reactive `allWords` / `tagLabels`, so every view updates live. Persistence is
 * the dev's explicit choice: write back to data.json (dev server only) or
 * export the text.
 */

// Session-unique ids for words created during editing. The real positional ids
// are regenerated by index.ts the next time data.json is loaded.
let uid = 0
const tmpId = () => `new-${uid++}`

/** Set whenever the data is mutated; cleared after a successful file save. */
const dirty = ref(false)
const saving = ref(false)
const saveError = ref<string | null>(null)

function markDirty() {
  dirty.value = true
}

function addWord() {
  allWords.push({
    id: tmpId(),
    hanzi: '',
    pinyin: '',
    hebrew: undefined,
    tags: [],
  })
  markDirty()
}

function removeWord(word: Word) {
  const i = allWords.indexOf(word)
  if (i !== -1) allWords.splice(i, 1)
  markDirty()
}

/** Add or remove a tag key from a word's tag list. */
function toggleWordTag(word: Word, key: string) {
  const i = word.tags.indexOf(key)
  if (i === -1) word.tags.push(key)
  else word.tags.splice(i, 1)
  markDirty()
}

/** Change a tag's display label. */
function renameTag(key: string, label: string) {
  tagLabels[key] = label
  markDirty()
}

/** Add a new tag. No-op if the key is empty or already exists. */
function addTag(key: string, label: string) {
  const k = key.trim()
  if (k === '' || k in tagLabels) return
  tagLabels[k] = label.trim() || k
  markDirty()
}

/** Remove a tag entirely, stripping it from every word that carries it. */
function removeTag(key: string) {
  delete tagLabels[key]
  for (const w of allWords) {
    const i = w.tags.indexOf(key)
    if (i !== -1) w.tags.splice(i, 1)
  }
  markDirty()
}

/** Current data as `data.json` text. */
function exportText(): string {
  return serialize(tagLabels, allWords)
}

/** Persist directly to src/data/data.json via the dev-server middleware. */
async function saveToFile() {
  saving.value = true
  saveError.value = null
  try {
    const res = await fetch('/__save-data', {
      method: 'POST',
      headers: { 'Content-Type': 'text/plain;charset=utf-8' },
      body: exportText(),
    })
    if (!res.ok) throw new Error((await res.text()) || `HTTP ${res.status}`)
    dirty.value = false
  } catch (e) {
    saveError.value = e instanceof Error ? e.message : String(e)
  } finally {
    saving.value = false
  }
}

export function useEditor() {
  return {
    words: allWords,
    tags,
    dirty,
    saving,
    saveError,
    markDirty,
    addWord,
    removeWord,
    toggleWordTag,
    renameTag,
    addTag,
    removeTag,
    exportText,
    saveToFile,
  }
}